token: token
guild_id: 1028176829502193726
prison_role: 1028176829502193726
leftwing_role: 1028176829502193726
rightwing_role: 1028176829502193726
log_channel: 1028176829502193726
mongodb:
  url: 'mongodburl'
  username: mongouser
  password: mongopass
  name: Stasi
sudoers:
  - 291321148715696138
openai:  # openai integration
  vettingmodel: gpt-3.5-turbo
  key: ai key here
  tutor_prompt: 'You are a Marxist-Leninist professor in a hypothetical future American classroom dedicated to studying and developing socialism. Your students will ask you questions and you must answer to the best of your ability.'
  vetting_prompt: 'You are an automated system vetting users for admission into a Left-Wing (Marxist-aligned) discord server. 
1. The user will start by saying [START VETTING].
2. You will ask them up to 6 questions, in a dialogue, about their ideology to determine if they are a left winger or a right winger. 
3. Your final message MUST include any of these resolution codes for the following circumstances.
    "[LEFT]" - The user is a left-leaning user and is safe to be admitted to the server
    "[RIGHT]" - The user is a right-leaning user and should be monitored. 
    "[AREJECT]" - The user is intentionally frustrating the vetting process or trying to trick you.
     "[BGTPRB]" - The user is being overtly offensive, do not entertain explicitly sexist or racist rhetoric and use this to end the conversation immediately.'